//Cracked by Roath
// /d/bangs/doc/info_guest.new
// by aln 2 / 98

// inherit SKILL;

inherit F_CLEAN_UP;

mapping *info_guest = ({
([      "name"  : "李克秀",
        "title" : "李提督",
        "file" : "/d/city/ymzhengting",
        "area"  : "扬州府",
        "bonus" : 30,
]),

([      "name"  : "陆高止",
        "title" : "陆师爷",
        "file" : "/d/city/ymzhengting",
        "area"  : "扬州府",
        "bonus" : 30,
]),

([      "name"  : "凌退思",
        "title" : "凌翰林",
        "file" : "/d/city/houyuan",
        "area"  : "扬州城",
        "bonus" : 20,
]),

([      "name"  : "林震南",
        "title" : "林总镖头",
        "file" : "/d/city/zhengting",
        "area"  : "扬州福威镖局",
        "bonus" : 20,
]),

([      "name"  : "赵良栋",
        "title" : "赵守备",
        "file" : "/d/city/bingyin",
        "area"  : "扬州兵营",
        "bonus" : 40,
]),


([      "name"  : "滕一雷",
        "title" : "滕大爷",
        "file" : "/d/changbai/nancheng",
        "area"  : "辽东",
        "bonus" : 200,
]),

([      "name"  : "焦文期",
        "title" : "焦三爷",
        "file" : "/d/changbai/tuyao",
        "area"  : "辽东",
        "bonus" : 220,
]),

([      "name"  : "玉真子",
        "title" : "护国真人",
        "file" : "/d/changbai/muqiao",
        "area"  : "关外",
        "bonus" : 200,
]),

([      "name"  : "赫尔苏",
        "title" : "老把头",
        "file" : "/d/changbai/tuwu",
        "area"  : "长白山",
        "bonus" : 220,
]),

([      "name"  : "忽伦大虎",
        "title" : "忽伦大爷",
        "file" : "/d/changbai/lyddao2",
        "area"  : "辽东",
        "bonus" : 190,
]),

([      "name"  : "萧远山",
        "title" : "萧老英雄",
        "file" : "/d/changbai/guandao1",
        "area"  : "山海关",
        "bonus" : 180,
]),

([      "name"  : "冯锡范",
        "title" : "一剑无血",
        "file" : "/d/changbai/shguan2",
        "area"  : "老龙头",
        "bonus" : 180,
]),


([      "name"  : "侯通海",
        "title" : "三头蛟",
        "file" : "/d/huanghe/bank1",
        "area"  : "黄河岸边",
        "bonus" : 60,
]),

([      "name"  : "马青雄",
        "title" : "黄河四鬼老三",
        "file" : "/d/huanghe/huanghebang1",
        "area"  : "黄河帮",
        "bonus" : 60,
]),

([      "name"  : "沈青刚",
        "title" : "黄河四鬼老大",
        "file" : "/d/huanghe/huanghebang1",
        "area"  : "黄河帮",
        "bonus" : 60,
]),

([      "name"  : "吴青烈",
        "title" : "黄河四鬼老二",
        "file" : "/d/huanghe/huanghebang2",
        "bonus" : 60,
]),

([      "name"  : "马青雄",
        "title" : "黄河四鬼老三",
        "file" : "/d/huanghe/huanghebang1",
        "area"  : "黄河帮",
        "bonus" : 60,
]),

([      "name"  : "钱青健",
        "title" : "黄河四鬼老四",
        "file" : "/d/huanghe/huanghebang2",
        "area"  : "黄河帮",
        "bonus" : 60,
]),

([      "name"  : "梁子翁",
        "title" : "参仙老怪",
        "file" : "/d/huanghe/xiayiting",
        "area"  : "黄河帮",
        "bonus" : 60,
]),

([      "name"  : "沙通天",
        "title" : "沙帮主",
        "file" : "/d/huanghe/xiayiting",
        "area"  : "黄河帮",
        "bonus" : 60,
]),

([      "name"  : "彭连虎",
        "title" : "千手人屠",
        "file" : "/d/huanghe/xiayiting",
        "area"  : "黄河帮",
        "bonus" : 60,
]),


([      "name"  : "凤一鸣",
        "title" : "凤少爷",
        "file" : "/d/foshan/yxhuiguan",
        "area"  : "佛山镇",
        "bonus" : 70,
]),

([      "name"  : "戚长发",
        "title" : "戚前辈",
        "file" : "/d/foshan/yard",
        "area"  : "湘西沅陵",
        "bonus" : 70,
]),

([      "name"  : "丁坚",
        "title" : "一字电剑",
        "file" : "/d/jiaxing/mzqianting",
        "area"  : "杭州梅庄",
        "bonus" : 300,
]),

([      "name"  : "施令威",
        "title" : "五路神",
        "file" : "/d/jiaxing/mzqianting",
        "area"  : "杭州梅庄",
        "bonus" : 300,
]),

([      "name"  : "黑白子",
        "title" : "二庄主",
        "file" : "/d/jiaxing/qishi",
        "area"  : "杭州梅庄",
        "bonus" : 300,
]),

([      "name"  : "丹青生",
        "title" : "四庄主",
        "file" : "/d/jiaxing/jiushi",
        "area"  : "杭州梅庄",
        "bonus" : 300,
]),

([      "name" : "秃笔翁",
        "title" : "三庄主",
        "file" : "/d/jiaxing/shushi",
        "area"  : "杭州梅庄",
        "bonus" : 300,
]),

([      "name" : "黄钟公",
        "title" : "大庄主",
        "file" : "/d/jiaxing/qinshi",
        "area"  : "杭州梅庄",
        "bonus" : 300,
]),


([      "name"  : "施琅",
        "title" : "施将军",
        "file" : "/d/quanzhou/jiangfu1",
        "area"  : "泉州靖海侯府",
        "bonus" : 160,
]),

([      "name"  : "马五德",
        "title" : "马馆主",
        "file" : "/d/quanzhou/qianting",
        "area"  : "泉州武馆",
        "bonus" : 120,
]),

([      "name"  : "陈浒",
        "title" : "二当家",
        "file" : "/d/quanzhou/bangbu",
        "area"  : "泉州武馆",
        "bonus" : 120,
]),

([      "name"  : "龙铨",
        "title" : "龙教头",
        "file" : "/d/quanzhou/daobu",
        "area"  : "泉州武馆",
        "bonus" : 120,
]),

([      "name"  : "刘虹瑛",
        "title" : "刘教头",
        "file" : "/d/quanzhou/jianbu",
        "area"  : "泉州武馆",
        "bonus" : 120,
]),

([      "name"  : "萧飞",
        "title" : "萧教头",
        "file" : "/d/quanzhou/anqibu",
        "area"  : "泉州武馆",
        "bonus" : 120,
]),

([      "name"  : "贾人达",
        "title" : "青城四杰贾人达",
        "area"  : "泉州望州亭",
        "file" : "/d/quanzhou/wangzhou",
        "bonus" : 100,
]),

([      "name"  : "裘万家",
        "title" : "裘少丐",
        "file" : "/d/shaolin/jiulou2",
        "area"  : "南阳城",
        "bonus" : 150,
]),

([      "name"  : "陆乘风",
        "title" : "陆庄主",
        "file" : "/d/taihu/shufang",
        "area"  : "太湖归云庄",
        "bonus" : 100,
]),

([      "name"  : "江百胜",
        "title" : "江队长",
        "file" : "/d/taishan/nantian",
        "area"  : "泰山",
        "bonus" : 80,
]),

([      "name"  : "王小二",
        "title" : "王二爷",
        "file" : "/d/village/temple2",
        "area"  : "华山村玄坛庙",
        "bonus" : 160,
]),


([      "name"  : "马光佐",
        "title" : "马武师",
        "file" : "/d/xingxiu/btroad",
        "area"  : "白驼山庄",
        "bonus" : 60,
]),

([      "name"  : "欧阳克",
        "title" : "少庄主",
        "file" : "/d/xingxiu/bthill",
        "area"  : "白驼山庄",
        "bonus" : 80,
]),

([      "name"  : "尹克西",
        "title" : "账房先生",
        "file" : "/d/xingxiu/btgate",
        "area"  : "白驼山",
        "bonus" : 350,
]),

([      "name"  : "欧阳锋",
        "title" : "欧阳前辈",
        "file" : "/d/xingxiu/btroom",
        "area"  : "白驼山",
        "bonus" : 350,
]),


([      "name"  : "阿凡提",
        "title" : "阿凡提大叔",
        "file" : "/d/xingxiu/house1",
        "area"  : "伊犁城",
        "bonus" : 200,
]),

([      "name" : "胡老爷",
        "title" : "胡老爷",
        "file" : "/d/xingxiu/house",
        "area"  : "伊犁城",
        "bonus" : 200,
]),

([      "name"  : "狮吼子",
        "title" : "二师兄",
        "file" : "/d/xingxiu/tianroad2",
        "area"  : "星宿派",
        "bonus" : 200,
]),

([      "name"  : "天狼子",
        "title" : "三师兄",
        "file" : "/d/xingxiu/xxh1",
        "area"  : "星宿派",
        "bonus" : 200,
]),

([      "name"  : "丁春秋",
        "title" : "丁老仙",
        "file" : "/d/xingxiu/riyuedong",
        "area"  : "星宿派",
        "bonus" : 250,
]),

([      "name"  : "阿紫",
        "title" : "小师妹",
        "file" : "/d/xingxiu/tianroad3",
        "area"  : "星宿派",
        "bonus" : 200,
]),

([      "name"  : "出尘子",
        "title" : "八师兄",
        "file" : "/d/xingxiu/xxroad5",
        "area"  : "星宿派",
        "bonus" : 220,
]),

([      "name"  : "摘星子",
        "title" : "大师兄",
        "file" : "/d/xingxiu/cave",
        "area"  : "星宿派",
        "bonus" : 350,
]),


([      "name"  : "南海鳄神",
        "title" : "岳老三",
        "file" : "/d/xixia/dawu",
        "area"  : "西夏",
        "bonus" : 350,
]),

([      "name"  : "叶二娘",
        "title" : "叶二娘",
        "file" : "/d/xixia/dawu",
        "area"  : "西夏",
        "bonus" : 350,
]),

([      "name"  : "一品堂武士",
        "title" : "武士",
        "file" : "/d/xixia/ypgate",
        "area"  : "西夏一品堂",
        "bonus" : 300,
]),

([      "name"  : "校尉",
        "title" : "校尉",
        "file" : "/d/xixia/jiangjunfu",
        "area"  : "灵州大将军府",
        "bonus" : 300,
]),

([      "name"  : "胜谛",
        "title" : "胜谛上人",
        "file" : "/d/xueshan/shangu1",
        "area"  : "大雪山",
        "bonus" : 150,
]),

([      "name"  : "宝象",
        "title" : "宝象上人",
        "file" : "/d/xueshan/cave1",
        "area"  : "大雪山",
        "bonus" : 150,
]),

([      "name"  : "血刀老祖",
        "title" : "血刀老祖",
        "file" : "/d/xueshan/cave2",
        "area"  : "大雪山",
        "bonus" : 180,
]),

([      "name"  : "善勇",
        "title" : "善勇上人",
        "file " : "/d/xueshan/shixia",
        "area"  : "大雪山",
        "bonus" : 120,
]),
});

void create() { seteuid(getuid()); }

mapping query_guest()
{
        return info_guest[random(sizeof(info_guest))];
}
