//Cracked by Kafei
// 侠客行现在有以下大区域

mapping region_names = ([
	"baituo"   : "西域白驼山",
	"beijing"  : "北京",
	"changbai" : "关外长白山",
	"city"     : "扬州",
	"dali"     : "云南大理",
	"death"    : "地狱",
	"emei"     : "四川峨嵋",
	"forest"   : "扬州郊外",
	"foshan"   : "广东佛山",
	"gaibang"  : "丐帮所在地",
	"hangzhou" : "杭州",
	"huanghe"  : "黄河边",
	"huangshan": "安徽黄山",
	"huashan"  : "华山",
	"island"   : "海外",
	"jiaxing"  : "嘉兴",
	"kunlun"   : "昆仑山",
	"miaojiang": "云南苗疆",
	"qilian"   : "祈连山",
	"quanzhou" : "福建泉州",
	"shaolin"  : "嵩山少林",
	"shenlong" : "辽东神龙岛",
	"taihu"    : "太湖边",
	"taishan"  : "山东泰山",
	"taohua"   : "东海桃花岛",
	"village"  : "华山村",
	"wizard"   : "仙界",
	"wudang"   : "湖北武当山",
	"xiakedao" : "侠客岛",
	"xingxiu"  : "西域",
	"xixia"    : "西夏",
	"xueshan"  : "藏边大雪山",
	"zhongnan" : "终南山",
        "lingjiu"  : "飘渺峰灵鹫宫"
]);
