//Cracked by Roath
// kane, created by 23/10/1997

mapping *force_list = ({
	([
		"family": "少林派",
		"force": "hunyuan-yiqi",
		"zheng_xie": 1,
		"gang_rou": 1,
		"attack": 0,
		"defense": 0,
		"dodge": 0,	
	]),
	([
		"family": "峨嵋派",
		"force": "linji-zhuang",
                "zheng_xie": 1,
                "gang_rou": -1,
        	"attack": 0,
        	"defense": 0,
        	"dodge": 0,
	]),
	([
		"family": "武当派",
		"force": "taiji-shengong",
                "zheng_xie": 1,
                "gang_rou": -1,
        	"attack": 0,
        	"defense": 0,
        	"dodge": 0,
	]),
	([
		"family": "丐帮",
		"force": "huntian-qigong",
                "zheng_xie": 1,
                "gang_rou": 1,
        	"attack": 0,
        	"defense": 0,
        	"dodge": 0,
	]),
	([
		"family": "星宿派",
		"force": "huagong-dafa",
                "zheng_xie": -1,
                "gang_rou": -1,
        	"attack": 0,
        	"defense": 0,
        	"dodge": 0,
	]),
	([
		"family": "桃花岛",
		"force": "bitao-xuangong",
                "zheng_xie": 0,
                "gang_rou": 0,
        	"attack": 0,
        	"defense": 0,
        	"dodge": 0,
	]),
	([
		"family": "白驼山",
		"force": "hamagong",
                "zheng_xie": -1,
                "gang_rou": 1,
        	"attack": 0,
        	"defense": 0,
        	"dodge": 0,
	]),
	([
		"family": "雪山派",
		"force": "longxiang-banruo",
                "zheng_xie": -1,
                "gang_rou": 1,
        	"attack": 0,
        	"defense": 0,
        	"dodge": 0,
	]),
	([
		"family": "血刀门",
		"force": "longxiang-banruo",
                "zheng_xie": -1,
                "gang_rou": 1,
        	"attack": 0,
        	"defense": 0,
        	"dodge": 0,
	]),
	([
		"family": "华山派",
		"force": "zixia-gong",
                "zheng_xie": 1,
                "gang_rou": 0,
        	"attack": 0,
        	"defense": 0,
        	"dodge": 0,
	]),
	([
		"family": "神龙教",
		"force": "dulong-dafa",
                "zheng_xie": -1,
                "gang_rou": -1,
        	"attack": 0,
        	"defense": 0,
        	"dodge": 0,
	]),
	([
		"family": "大理段家",
		"force": "kurong-changong",
                "zheng_xie": 1,
                "gang_rou": 1,
        	"attack": 0,
        	"defense": 0,
        	"dodge": 0,
	]),
	([
		"family": "明教",
		"force": "shenghuo-xuangong",
                "zheng_xie": 1,
                "gang_rou": 1,
        	"attack": 0,
        	"defense": 0,
        	"dodge": 0,
	]),
});
